name: DbApp

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure git settings
        run: |
              git config --global user.name "${{ secrets.USER_NAME }}"
              git config --global user.email "${{ secrets.USER_EMAIL }}"

      - name: Build for win-x64
        shell: bash 
        run: |
              cd ./app
              dotnet publish -c Release -r win-x64 --self-contained

      - name: Build for linux-x64
        shell: bash 
        run: |
              cd ./app
              dotnet publish -c Release -r linux-x64 --self-contained
            
      - name: Git push
        run: |
              git add .
              git commit -m "Update builds"
              git push

